config/routes.rb
Rails.application.routes.draw do   
  resources :affiliations
  resources :reviews
  resources :videos, only: [:index, :new, :create]
  resources :video_uploads, only: [:new, :create]
  root 'pages#home'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/profile' => 'profile#index'
  get '/profile/nameandrole' => 'profile#nameandrole'

  get '/cliente' => 'cliente#search'
  get '/cliente/function' => 'cliente#function'
  get '/cliente/managerprofile' => 'cliente#visualize'
  get '/cliente/events' => 'cliente#events' 

  # get '/cliente/createEvent' => 'cliente#createEvent'
  # get '/cliente/createEventConfirm' => 'cliente#createEventConfirm'

  # get "cliente/listEvent" , to: "cliente#listEvent"
  # get "cliente/deleteEvent" , to: "cliente#deleteEvent"

  # get "/cliente/event", to: "cliente#editEvent"
  # patch "/cliente/event", to: "cliente#reviewEvent"

  get '/manager' => 'manager#index'
  get '/manager/affiliazioni' => 'manager#affiliazioni'
  get '/manager/aziende' => 'manager#aziende'
  get '/manager/singleone' => 'manager#singleone'
  get '/manager/events' => 'manager#events' 

  get '/azienda' => 'azienda#index'
  get '/azienda/affiliazioni' => 'azienda#affiliazioni'
  
  get '/affiliations/accept' => 'affiliation#accept'

  get '/utility/annulla' => 'utility#annulla'
  
  get '/reviews' => 'review#index'
  # Defines the root path route ("/")
  # root "articles#index"
  get "calendar/createCalendar" , to: "calendar#create"
  get "calendar/updateCalendar" , to: "calendar#update"
  get "calendar/deleteCalendar" , to: "calendar#delete"

  get "calendar/createEvent" , to: "calendar#createEvent"
  post "calendar/createEventConfirm" , to: "calendar#createEventConfirm"
  get "calendar/createEventConfirm" , to: "calendar#createEventConfirm"
  get "calendar/listEvent" , to: "calendar#listEvent"
  get "calendar/deleteEvent" , to: "calendar#deleteEvent"

  get "/event", to: "calendar#editEvent"
  patch "/event", to: "calendar#reviewEvent"

  get "/YTProva", to: "youtube#youtubeListProva"

  get "/oauth2callback", to: "youtube#oauth2callback"

  #per yt
  get "/inizio", to: "yt_menu#index"
  get "/videos", to: "videos#index"
  get "/provayt1", to: "youtube#list"
  get "/provayt2", to: "youtube#youtubeListProva"
  get "/provayt3", to: "youtube#upload"
  post 'upload_video', to: 'youtube#upload', as: 'upload'

  get "/list_subs", to: "youtube#list_subs"
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name # assuming the user model has a name
      user.avatar_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
      user.access_token = auth.credentials.token
      user.refresh_token = auth.credentials.refresh_token
    end
  end
  
  has_one_attached :avatar
end

app/models/video.rb
class Video < ApplicationRecord
    YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

    validates :link, presence: true, format: YT_LINK_FORMAT
end

app/models/video_observer.rb
class VideoObserver < ActiveRecord::Observer
    def before_save(resource)
      video = Yt::Video.new url: resource.link
      resource.uid = video.id
      resource.title = video.title
      resource.likes = video.like_count
      resource.dislikes = video.dislike_count
      resource.published_at = video.published_at
    rescue Yt::Errors::NoItems
      resource.title = ''
    end
  end

app/models/video_upload.rb
class VideoUpload < ApplicationRecord
    attribute :file, :binary
    attribute :title, :binary
    attribute :description, :text
  
    validates :file, presence: true
    validates :title, presence: true

    def upload!(user)
        account = Yt::Account.new access_token: user.token
        account.upload_video self.file, title: self.title, description: self.description
    end
end

app/controllers/azienda_controller.rb
class AziendaController < ApplicationController

    before_action:require_user_logged_in!
    before_action:are_you_an_azienda

    def index
        @users = User.all
    end

    def affiliazioni
        @affiliazioni= Affiliation.all
    end
  
  end
  

app/controllers/manager_controller.rb
class ManagerController < ApplicationController

    before_action:require_user_logged_in!
    before_action:are_you_a_manager

    def index
        @users=User.all
    end

    def affiliazioni
        @affiliazioni=Affiliation.all
    end

    def aziende
        @users=User.all
        @cliente= params[:id]
        @manager= current_user.id
        is_it_your_client(@manager,@cliente)
    end

    def singleone
        @cliente= User.find(params[:cliente])
        is_it_your_client(current_user.id,@cliente.id)
    end

    def events
        @cliente= User.find(params[:cliente])
        @events=Event.all
        is_it_your_client(current_user.id,@cliente.id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
    if current_user 
      if !current_user.ruolo
        redirect_to '/users/edit' and return
        flash.now[:notice] = 'Message sent!'
      end
    end
    render :layout => 'home'
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to root_url
    else
      render :new
    end
  end
  
  private
  
  def video_params
    params.require(:video).permit(:link)
  end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/video_uploads_helper.rb
module VideoUploadsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/yt_menu_helper.rb
module YtMenuHelper
end

app/views/manager/affiliazioni.html.erb
<!DOCTYPE html>
<html amp >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="" type="">
  
  <title>ManageMyYoutube</title>
  
<link rel="canonical" href="bookstore.html">
 <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
<noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="old stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="old stylesheet"><link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo:100,300,400,500,700,800,900" rel="stylesheet">

    <script async  src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
    
    
    
</head>
<body>

<section class="cid-rslFJC9ynI" id="menu01-4n">
	
	<!-- mine-navbar -->
	<nav class="mine-navbar mine-navbar-dropdown mine-navbar-expand-lg mine-navbar-fixed-top">
		<div class="menu-mine-container mine-container-fluid">
			
			<div class="mine-navbar-brand">
				<div class="mine-navbar-logo">
					<img src="/assets/local/logomyytmanager.png" style="width:80px;padding-right:10px">
				</div>
				<span class="mine-navbar-caption-wrap"><a class="mine-navbar-caption mbr-semibold text-black text-decoration-none display-5" style="font-size: 2rem" href="/">ManageMyYoutube</a></span>
			</div>

            <div class="mine-btns">
                <% if current_user %>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7 text-decoration-none" href="/profile">Profile</a>
                    </div>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete, class:"mine-btnlogout" %>
                    </div>
                
                <% else%>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                
                    <a class="mine-btn mine-btn-md mine-btn-white mbr-semibold display-7" href="users/sign_in">Login</a>
                    <%= link_to "Login", new_user_session_path %>
                    
                </div>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                    <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7" href="users/sign_up">Sign Up</a>
                </div>
                <%end %>
            </div>

		</div>
	</nav>

	
	<!-- </div> -->
</section>

<section class="header3 cid-rsq6I1iuyl">
    <%def withoutLast5(userAvatarUrl)
        if userAvatarUrl
          return userAvatarUrl[0..-6]+"s580-c"
        else 
          return "https://blogtimenow.com/wp-content/uploads/2014/06/hide-facebook-profile-picture-notification.jpg"
        end
      end    
    %>

    <div class="container d-flex flex-row" style="height:270px">
        <div class="d-flex flex-column col-12">
            <h2 class="py-3">Lista Affiliazioni</h2>

            <!--DA IMPLEMENTARE ! -->
            
            <div class="d-flex flex-column gap-2">
                <% @affiliazioni.each do |affiliazione| %>
                    <%if affiliazione.manager.to_i==current_user.id && affiliazione.status!="accepted" && affiliazione.azienda==""%> 
                        <% @cliente= User.find(affiliazione.cliente)%>                    
                        <div class="d-flex flex-row gap-5 align-items-center border p-4 text-black">

                        <div>
                            <% if @cliente.avatar.attached?%>
                                <%= image_tag @cliente.avatar,class:"rounded-circle",height:100,width:100 %>
                            <% else %>
                                <img src="<%=withoutLast5(@cliente.avatar_url)%>" alt="avatar" class="rounded-circle" style="width: 100px;">
                            <%end%>
                        </div>
                            
                        <div>
                            <p class="font-weight-bold" style="font-weight: bold"><%= @cliente.full_name %></p>
                        </div>

                        <div>
                            <p><%= @cliente.email%></p>
                        </div>

                        <div class="accept-btns d-flex fleex-row gap-3" style="margin-left:auto">
                            <a href="/affiliations/<%= affiliazione.id%>"><button type="button" class="btn btn-success">Accetta</button></a>
                            <%= button_to "Rifiuta", affiliazione, method: :delete, class:"btn btn-danger" %>
                        </div>

                        <br>
                    </div>
                    <%end%>
                    <%if affiliazione.azienda.to_i==current_user.id && affiliazione.status!="accepted"%> 
                        <% @cliente= User.find(affiliazione.cliente)%>
                        <% @manager= User.find(affiliazione.manager)%>                    
                        <div class="d-flex flex-row gap-5 align-items-center border p-4 text-black">

                        <div>
                            <% if @cliente.avatar.attached?%>
                                <%= image_tag @cliente.avatar,class:"rounded-circle",height:100,width:100 %>
                            <% else %>
                                <img src="<%=withoutLast5(@cliente.avatar_url)%>" alt="avatar" class="rounded-circle" style="width: 100px;">
                            <%end%>
                        </div>
                            
                        <div>
                            <p class="font-weight-bold" style="font-weight: bold"><%= @cliente.full_name %></p>
                        </div>

                        <div>
                            <p><%= @cliente.email%></p>
                        </div>

                        <div class="accept-btns d-flex fleex-row gap-3" style="margin-left:auto">
                            <a href="/affiliations/<%= affiliazione.id%>"><button type="button" class="btn btn-success">Accetta</button></a>
                            <%= button_to "Rifiuta", affiliazione, method: :delete, class:"btn btn-danger" %>
                        </div>

                        <br>
                    </div>
                    <%end%>

                <% end %>

            </div>
            
        </div>
    </div>

</section>

app/views/manager/singleone.html.erb
<!DOCTYPE html>
<html amp >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="" type="">
  
  <title>ManageMyYoutube</title>
  
<link rel="canonical" href="bookstore.html">
 <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
<noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="old stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="old stylesheet"><link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo:100,300,400,500,700,800,900" rel="stylesheet">

    <script async  src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
    
    
    
</head>
<body>

    <section class="cid-rslFJC9ynI" id="menu01-4n">
        
        <!-- mine-navbar -->
        <nav class="mine-navbar mine-navbar-dropdown mine-navbar-expand-lg mine-navbar-fixed-top">
            <div class="menu-mine-container mine-container-fluid">
                
                <div class="mine-navbar-brand">
                    <div class="mine-navbar-logo">
                        <img src="/assets/local/logomyytmanager.png" style="width:80px;padding-right:10px">
                    </div>
                    <span class="mine-navbar-caption-wrap"><a class="mine-navbar-caption mbr-semibold text-black text-decoration-none display-5" style="font-size: 2rem" href="/">ManageMyYoutube</a></span>
                </div>

                <div class="mine-btns">
                    <% if @cliente %>
                        <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                            <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7 text-decoration-none" href="/profile">Profile</a>
                        </div>
                        <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                            <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete, class:"mine-btnlogout" %>
                        </div>
                    
                    <% else%>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                    
                        <a class="mine-btn mine-btn-md mine-btn-white mbr-semibold display-7" href="users/sign_in">Login</a>
                        <%= link_to "Login", new_user_session_path %>
                        
                    </div>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7" href="users/sign_up">Sign Up</a>
                    </div>
                    <%end %>
                </div>

            </div>
        </nav>

        
        <!-- </div> -->
    </section>

  <section style="background-color: white;">
    <div class="container py-5">
      <%def withoutLast5(user)
          if @cliente.avatar_url
            return @cliente.avatar_url[0..-6]+"s580-c"
          else 
            return "https://blogtimenow.com/wp-content/uploads/2014/06/hide-facebook-profile-picture-notification.jpg"
          end
        end    
      %>

      <div class="row">

        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
                <% if !@cliente.avatar.attached?%>
                <img src="<%=withoutLast5(@cliente.avatar_url)%>" alt="avatar"
                class="rounded-circle" style="width: 150px;">
                <% else %>
                <%= image_tag @cliente.avatar,class:"rounded-circle",height:150,width:150 %>
                <%end%>
                <h5 class="my-3 text-capitalize"><%= @cliente.full_name %></h5>
                <p class="text-muted mb-1 text-capitalize"><%= @cliente.ruolo %></p>

                <% @affiliazione=Affiliation.where(cliente: @cliente.id.to_s).where(manager: current_user.id.to_s).where(status: "accepted").take%>
                <a href="/manager/aziende?id=<%=@cliente.id%>" class="btn btn-outline-danger mt-2" style="margin-left:auto">Affilia ad un'azienda</a>
            </div>
          </div>
        </div>

        <div class="col-lg-8">

            <div class="card mb-4">
            <div class="card-body">

                <div class="row">
                <div class="col-sm-3">
                    <p class="mb-0">Nome</p>
                </div>
                <div class="col-sm-9">
                    <p class="text-muted mb-0 text-capitalize"><%= @cliente.full_name %></p>
                </div>
                </div>

                <hr>

                <div class="row">
                <div class="col-sm-3">
                    <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @cliente.email %></p>
                </div>
                </div>

            </div>
            </div>

            <!--Youtube e Calendar Functions-->
            <div class="d-flex flex-row mb-4">
            
            <div class="d-flex justify-content-center col-6" style="border-right: 1px solid grey;">
                <h4>Funzioni Youtube</h4>
                <div class="d-flex flex-column">
                    <hr>
                    <ul class="list-group">
                        <div class="d-flex flex-row gap-3 align-items-center">
                            <div>
                                <%= link_to list_subs_path(userID: @cliente.id.to_i) do %>
                                    <li class="btn btn-success mt-1" style="width:100%">Visualizza Iscritti</li>
                                <% end %>
                            </div>
                        </div>
                    </ul>
                    <hr>
                </div>
            </div>

            <div class="d-flex flex-column align-items-center col-6">
                <h4>Funzioni Calendar</h4>
                
                <div class="d-flex flex-column">
                                <hr>
                                <ul class="list-group">

                                    <%if !Calendar.where(userId: @cliente.id.to_s).where(managerId: current_user.id.to_s).take%>
                                        <%= link_to calendar_createCalendar_path(userID: @cliente.id.to_i) do %>
                                            <li class="btn btn-success mt-1" style="width:100%">Crea Calendario</li>
                                        <% end %>
                                    <%else%>
                                    <div class="d-flex flex-row gap-3 align-items-center">
                                        <div>
                                            <%= link_to 'http://calendar.google.com/', target: :_blank do %>
                                                <li class="btn btn-warning mt-1" style="width:100%">Visualizza Calendario</li>
                                            <% end %>
                                            <%= link_to calendar_deleteCalendar_path(userID: @cliente.id) do %>
                                                <li class="btn btn-danger mt-1" style="width:100%">Elimina Calendario</li>
                                            <% end %>
                                            <br>
                                            <hr>
                                            
                                            <%= link_to calendar_createEvent_path(userID: @cliente.id) do %>
                                                <li class="btn btnevent mt-1" style="width:100%; background-color: rgb(169, 249, 255);">Crea Evento</li>
                                            <% end %>
                                                <a href="/manager/events?cliente=<%=@cliente.id.to_s%>" class="btn btnevent mt-1" style="width:100%;  background-color: rgb(98, 245, 255)">Visualizza Eventi</a>
                                            <!--
                                            <%= link_to calendar_listEvent_path(userID: @cliente.id) do %>
                                                <li class="btn btnevent mt-1" style="width:100%;  background-color: rgb(98, 245, 255)";>Modifica Evento</li>
                                            <% end %>
                                            <%= link_to calendar_deleteEvent_path(userID: @cliente.id) do %>
                                                <li class="btn btnevent mt-1" style="width:100%; background-color:rgb(4, 238, 255);">Elimina Evento</li>
                                            <% end %>
                                            -->
                                        </div>
                                    </div>
                                    <%end%>
                                </ul>
                            </div>
            </div>

            </div>

        </div>

      </div>
    </div>
  </section>