config/routes.rb
Rails.application.routes.draw do   
  resources :affiliations
  resources :reviews
  resources :videos, only: [:index, :new, :create]
  resources :video_uploads, only: [:new, :create]
  root 'pages#home'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/profile' => 'profile#index'
  get '/profile/nameandrole' => 'profile#nameandrole'

  get '/cliente' => 'cliente#search'
  get '/cliente/function' => 'cliente#function'
  get '/cliente/managerprofile' => 'cliente#visualize'
  get '/cliente/events' => 'cliente#events' 

  # get '/cliente/createEvent' => 'cliente#createEvent'
  # get '/cliente/createEventConfirm' => 'cliente#createEventConfirm'

  # get "cliente/listEvent" , to: "cliente#listEvent"
  # get "cliente/deleteEvent" , to: "cliente#deleteEvent"

  # get "/cliente/event", to: "cliente#editEvent"
  # patch "/cliente/event", to: "cliente#reviewEvent"

  get '/manager' => 'manager#index'
  get '/manager/affiliazioni' => 'manager#affiliazioni'
  get '/manager/aziende' => 'manager#aziende'
  get '/manager/singleone' => 'manager#singleone'
  get '/manager/events' => 'manager#events' 

  get '/azienda' => 'azienda#index'
  get '/azienda/affiliazioni' => 'azienda#affiliazioni'
  
  get '/affiliations/accept' => 'affiliation#accept'

  get '/utility/annulla' => 'utility#annulla'
  
  get '/reviews' => 'review#index'
  # Defines the root path route ("/")
  # root "articles#index"
  get "calendar/createCalendar" , to: "calendar#create"
  get "calendar/updateCalendar" , to: "calendar#update"
  get "calendar/deleteCalendar" , to: "calendar#delete"

  get "calendar/createEvent" , to: "calendar#createEvent"
  post "calendar/createEventConfirm" , to: "calendar#createEventConfirm"
  get "calendar/createEventConfirm" , to: "calendar#createEventConfirm"
  get "calendar/listEvent" , to: "calendar#listEvent"
  get "calendar/deleteEvent" , to: "calendar#deleteEvent"

  get "/event", to: "calendar#editEvent"
  patch "/event", to: "calendar#reviewEvent"

  get "/YTProva", to: "youtube#youtubeListProva"

  get "/oauth2callback", to: "youtube#oauth2callback"

  #per yt
  get "/inizio", to: "yt_menu#index"
  get "/videos", to: "videos#index"
  get "/provayt1", to: "youtube#list"
  get "/provayt2", to: "youtube#youtubeListProva"
  get "/provayt3", to: "youtube#upload"
  post 'upload_video', to: 'youtube#upload', as: 'upload'

  get "/list_subs", to: "youtube#list_subs"
end

app/controllers/youtube_controller.rb
require 'google/apis/youtube_v3'
require "google/api_client/client_secrets.rb"

require 'googleauth'
require 'googleauth/stores/file_token_store'
require 'fileutils'


class YoutubeController < ApplicationController
  # YOUTUBE_UPLOAD_SCOPE = 'https://www.googleapis.com/auth/youtube.upload'
  # YOUTUBE_API_SERVICE_NAME = 'youtube'
  # YOUTUBE_API_VERSION = 'v3'

  SCOPE = ['https://www.googleapis.com/auth/calendar',
    'https://www.googleapis.com/auth/calendar.events',
    'https://www.googleapis.com/auth/calendar.events.readonly',
    'https://www.googleapis.com/auth/calendar.readonly',
    'https://www.googleapis.com/auth/calendar.settings.readonly',
    'https://www.googleapis.com/auth/youtube',
    'https://www.googleapis.com/auth/youtube.force-ssl',
    'https://www.googleapis.com/auth/youtube.readonly',
    'https://www.googleapis.com/auth/youtube.upload',
    'https://www.googleapis.com/auth/youtubepartner',
    'https://www.googleapis.com/auth/youtubepartner-channel-audit']

  CLIENT_SECRETS_PATH = 'app/controllers/client_secret.json'
  CREDENTIALS_PATH = "app/controllers/youtube-quickstart-ruby-credentials.yaml"
  REDIRECT_URI = 'http://localhost:3000/oauth2callback'
  APPLICATION_NAME = 'Progetto LASSI'

  def list
    client = get_google_youtube_client current_user

    part = 'snippet,contentDetails,statistics'

    #METODO PER OTTENERE IL CANALE RELATIVO AL CLIENTE

    @mineresponse= client.list_channels(part, "mine":true).to_json

    @response = client.list_channels(part, "id": ["UC_x5XG1OV2P6uZZ5FSM9Ttw"]).to_json

    item = JSON.parse(@response).fetch("items")[0]

    @lisResp = "This channel's ID is #{item.fetch("id")}. " + "Its title is '#{item.fetch("snippet").fetch("title")}', and it has " + "#{item.fetch("statistics").fetch("viewCount")} views."
      
  rescue Google::Apis::AuthorizationError
    secrets = Google::APIClient::ClientSecrets.new({
        "web" => {
          "access_token" => current_user.access_token,
          "refresh_token" => current_user.refresh_token,
          "client_id" => ENV["GOOGLE_OAUTH_CLIENT_ID"],
          "client_secret" => ENV["GOOGLE_OAUTH_CLIENT_SECRET"]
        }
    })
    client.authorization = secrets.to_authorization
    client.authorization.grant_type = "refresh_token"

    client.authorization.refresh!
    current_user.update_attribute(:access_token, client.authorization.access_token)
    current_user.update_attribute(:refresh_token, client.authorization.refresh_token)

    retry
  end

  def list_subs
    # client = get_google_youtube_client current_user
    # youtube = Google::Apis::YoutubeV3::YouTubeService.new
    # youtube.authorization = authorize

    if current_user.ruolo === "manager"
      cliente = User.find(params[:userID])
      youtube = get_google_youtube_client cliente
    else
      youtube = get_google_youtube_client current_user
    end

    @subsCount = youtube.list_channels(
      "snippet,contentDetails,statistics", 
      :mine => true
    )

    @subsList = youtube.list_subscriptions("subscriberSnippet", my_subscribers: true)

  rescue Google::Apis::AuthorizationError
    secrets = Google::APIClient::ClientSecrets.new({
        "web" => {
          "access_token" => current_user.access_token,
          "refresh_token" => current_user.refresh_token,
          "client_id" => ENV["GOOGLE_OAUTH_CLIENT_ID"],
          "client_secret" => ENV["GOOGLE_OAUTH_CLIENT_SECRET"]
        }
    })
    client.authorization = secrets.to_authorization
    client.authorization.grant_type = "refresh_token"

    client.authorization.refresh!
    current_user.update_attribute(:access_token, client.authorization.access_token)
    current_user.update_attribute(:refresh_token, client.authorization.refresh_token)

    retry
  end

  # def youtubeListProva
  #   client = get_google_youtube_client current_user
  #   @dati = client.list_channels("UCJgEAT_2X9rkjjyq5cfZ-GQ")
      
  # rescue Google::Apis::AuthorizationError
  #     secrets = Google::APIClient::ClientSecrets.new({
  #         "web" => {
  #           "access_token" => current_user.access_token,
  #           "refresh_token" => current_user.refresh_token,
  #           "client_id" => ENV["GOOGLE_OAUTH_CLIENT_ID"],
  #           "client_secret" => ENV["GOOGLE_OAUTH_CLIENT_SECRET"]
  #         }
  #     })
  #     client.authorization = secrets.to_authorization
  #     client.authorization.grant_type = "refresh_token"

  #     client.authorization.refresh!
  #     current_user.update_attribute(:access_token, client.authorization.access_token)
  #     current_user.update_attribute(:refresh_token, client.authorization.refresh_token)
      
  #     retry
  # end

  # def uploadProva
  #   client = get_google_youtube_client current_user
  #   youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)

  #   respond_to do |format|
  #     format.html { render :upload_video }
  #   end
  #   required = [:name, :email, :reply, :feedback_type, :message]
  #   form_complete = true
  #   required.each do |f|
  #     if params.has_key? f and not params[f].blank?
  #       # that's good news. do nothing
  #     else
  #       form_complete = false
  #     end
  #   end
  #   if form_complete
  #     form_status_msg = 'Thank you for your feedback!'
  #   else
  #     form_status_msg = 'Please fill in all the remaining form fields and resubmit.'
  #   end
  #   format.html { render :contact, locals: { status_msg: form_status_msg } }

  #   begin
  #     body = {
  #       :snippet => {
  #         :title => opts[:title],
  #         :description => opts[:description],
  #         :tags => opts[:keywords].split(','),
  #         :categoryId => opts[:category_id],
  #       },
  #       :status => {
  #         :privacyStatus => opts[:privacy_status]
  #       }
  #     }
  
  #     videos_insert_response = client.execute!(
  #       :api_method => youtube.videos.insert,
  #       :body_object => body,
  #       :media => Google::APIClient::UploadIO.new(opts[:file], 'video/*'),
  #       :parameters => {
  #         :uploadType => 'resumable',
  #         :part => body.keys.join(',')
  #       }
  #     )
  
  #     videos_insert_response.resumable_upload.send_all(client)
  
  #     @inserted = "Video id '#{videos_insert_response.data.id}' was successfully uploaded."
  #   rescue Google::APIClient::TransmissionError => e
  #     @resBody = e.result.body
  #   end
      
  # rescue Google::Apis::AuthorizationError
  #     secrets = Google::APIClient::ClientSecrets.new({
  #         "web" => {
  #           "access_token" => current_user.access_token,
  #           "refresh_token" => current_user.refresh_token,
  #           "client_id" => ENV["GOOGLE_OAUTH_CLIENT_ID"],
  #           "client_secret" => ENV["GOOGLE_OAUTH_CLIENT_SECRET"]
  #         }
  #     })
  #     client.authorization = secrets.to_authorization
  #     client.authorization.grant_type = "refresh_token"

  #     client.authorization.refresh!
  #     current_user.update_attribute(:access_token, client.authorization.access_token)
  #     current_user.update_attribute(:refresh_token, client.authorization.refresh_token)
  #     retry
  # end

  # def upload
  #   respond_to do |format|
  #     format.html { render :upload_video }
  #   end
  #   required = [:name, :email]
  #   form_complete = true
  #   required.each do |f|
  #     if params.has_key? f and not params[f].blank?
  #       # that's good news. do nothing
  #     else
  #       form_complete = false
  #     end
  #   end
  #   if form_complete
  #     format.html { render :name }
  #     form_status_msg = 'Thank you for your feedback!'
  #   else
  #     form_status_msg = 'Please fill in all the remaining form fields and resubmit.'
  #   end
  # end

  def get_google_youtube_client current_user
    client = Google::Apis::YoutubeV3::YouTubeService.new

    return unless (current_user.present? && current_user.access_token.present? && current_user.refresh_token.present?)
    secrets = Google::APIClient::ClientSecrets.new({
      "web" => {
        "access_token" => current_user.access_token,
        "refresh_token" => current_user.refresh_token,
        "client_id" => ENV["GOOGLE_OAUTH_CLIENT_ID"],
        "client_secret" => ENV["GOOGLE_OAUTH_CLIENT_SECRET"]
      }
    })
    begin
      client.authorization = secrets.to_authorization
      client.authorization.grant_type = "refresh_token"

      if !current_user.present?
        client.authorization.refresh!
        current_user.update_attributes(
          access_token: client.authorization.access_token,
          refresh_token: client.authorization.refresh_token
        )
      end
    rescue => e
      flash[:error] = 'Your token has been expired. Please login again with google.'
      redirect_to :back
    end
    client
  end

  def authorize
    FileUtils.mkdir_p(File.dirname(CREDENTIALS_PATH))
  
    client_id = Google::Auth::ClientId.from_file(CLIENT_SECRETS_PATH)
    token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH)
    authorizer = Google::Auth::UserAuthorizer.new(
      client_id, SCOPE, token_store)
    user_id = 'default'
    credentials = authorizer.get_credentials(user_id)
    if credentials.nil?
      url = authorizer.get_authorization_url(base_url: REDIRECT_URI)
      puts "Open the following URL in the browser and enter the " +
            "resulting code after authorization"
      puts url
      code = gets
      credentials = authorizer.get_and_store_credentials_from_code(
        user_id: user_id, code: code, base_url: REDIRECT_URI)
    end
    credentials
  end

  def oauth2callback
  end
end

app/views/youtube/list.html.erb
<!DOCTYPE html>
<html amp >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="" type="">
  
  <title>ManageMyYoutube</title>
  
<link rel="canonical" href="bookstore.html">
 <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
<noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="old stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="old stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo:100,300,400,500,700,800,900" rel="stylesheet">

    <script async  src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
    
    
    
</head>
<body>

<section class="cid-rslFJC9ynI" id="menu01-4n">
	
	<!-- mine-navbar -->
	<nav class="mine-navbar mine-navbar-dropdown mine-navbar-expand-lg mine-navbar-fixed-top">
		<div class="menu-mine-container mine-container-fluid">
			
			<div class="mine-navbar-brand">
				<div class="mine-navbar-logo">
					<img src="/assets/local/logomyytmanager.png" style="width:80px;padding-right:10px">
				</div>
				<span class="mine-navbar-caption-wrap"><a class="mine-navbar-caption mbr-semibold text-black text-decoration-none display-5" style="font-size: 2rem" href="/">ManageMyYoutube</a></span>
			</div>

            <div class="mine-btns">
                <% if current_user %>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7 text-decoration-none" href="/profile">Profile</a>
                    </div>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete, class:"mine-btnlogout" %>
                    </div>
                
                <% else%>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                
                    <a class="mine-btn mine-btn-md mine-btn-white mbr-semibold display-7" href="users/sign_in">Login</a>
                    <%= link_to "Login", new_user_session_path %>
                    
                </div>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                    <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7" href="users/sign_up">Sign Up</a>
                </div>
                <%end %>
            </div>

		</div>
	</nav>

	
	<!-- </div> -->
</section>

<% item= JSON.parse(@mineresponse).fetch("items")[0] %>

<% snippet = item.fetch("snippet") %>
<% statistics = item.fetch("statistics")%>

<div class="spacer py-5"></div>
<div class="container pt-1 d-flex flex-row justify-content-center gap-3 px-5">
    <div>
        <img src="<%=snippet.fetch("thumbnails").fetch("high").fetch("url")%>" alt="avatar"
                    class="rounded-circle border" style="width: 150px;">
    </div>
    <div class="ytpicture d-flex flex-row px-5 gap-5">
        <div  class="d-flex flex-column justify-content-center">
            <h2 class="text-decoration-underline pb-3">Informazioni di <%= snippet.fetch("title")%></h2>
            <p><strong>Iscritti:</strong>  <%= statistics.fetch("subscriberCount")%></p>
            <p><strong>Numero di video:</strong>  <%= statistics.fetch("videoCount")%></p>
            <p><strong>Visualizzazioni del canale:</strong>  <%= statistics.fetch("viewCount")%></p>
        </div>
        
    </div>
</div>

<div class="container d-flex flex-row gap-3  pb-5 px-5">
    <div class="d-flex flex-column justify-content-center">
        <div class="py-4">
            <h3>Descrizione:</h3>
        </div>
        <div>
            <p><%= snippet.fetch("description")%></p>
        </div>
    </div>
</div>

app/views/youtube/list_subs.html.erb
<!DOCTYPE html>
<html amp >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="" type="">
  
  <title>ManageMyYoutube</title>
  
<link rel="canonical" href="bookstore.html">
 <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
<noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="old stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="old stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo:100,300,400,500,700,800,900" rel="stylesheet">

    <script async  src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
    
    
    
</head>
<body>

<section class="cid-rslFJC9ynI" id="menu01-4n">
	
	<!-- mine-navbar -->
	<nav class="mine-navbar mine-navbar-dropdown mine-navbar-expand-lg mine-navbar-fixed-top">
		<div class="menu-mine-container mine-container-fluid">
			
			<div class="mine-navbar-brand">
				<div class="mine-navbar-logo">
					<img src="/assets/local/logomyytmanager.png" style="width:80px;padding-right:10px">
				</div>
				<span class="mine-navbar-caption-wrap"><a class="mine-navbar-caption mbr-semibold text-black text-decoration-none display-5" style="font-size: 2rem" href="/">ManageMyYoutube</a></span>
			</div>

            <div class="mine-btns">
                <% if current_user %>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7 text-decoration-none" href="/profile">Profile</a>
                    </div>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete, class:"mine-btnlogout" %>
                    </div>
                
                <% else%>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                
                    <a class="mine-btn mine-btn-md mine-btn-white mbr-semibold display-7" href="users/sign_in">Login</a>
                    <%= link_to "Login", new_user_session_path %>
                    
                </div>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                    <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7" href="users/sign_up">Sign Up</a>
                </div>
                <%end %>
            </div>

		</div>
	</nav>

	
	<!-- </div> -->
</section>

<div class="spacer py-5"></div>

<div class="container d-flex flex-row">
    <div class="d-flex flex-column col-12">
        <h2 class="py-3">Lista Iscritti </h2>
        <h6 class="pb-3">(Sono visualizzati soltanto i canali con Sublist Pubblica)</h6>

        <!--DA IMPLEMENTARE ! -->
        
        <div class="d-flex flex-column gap-2">
            <% @subsList.items.each do |item| %>
                <div class="d-flex flex-row gap-5 align-items-center border managerline p-4 text-black">
                    <div>
                        <img src="<%=item.subscriber_snippet.thumbnails.high.url%>" alt="avatar"
                    class="rounded-circle border" style="width: 100px;">
                    </div>
                        
                    <div>
                        <p class="font-weight-bold text-capitalize" style="font-weight: bold">  <%= item.subscriber_snippet.title %></p>
                    </div>

                </div>

            <% end %>

        </div>
        
    </div>
</div>

app/views/youtube/upload_video.html.erb
 <%= form_with url: upload_path, local: true, method: :post do %>
    <div>
        <%= label_tag "name" %>
        <%= text_field_tag "name", nil %>
    </div>
    <div>
        <%= label_tag "email" %>
        <%= email_field_tag "email", nil %>
    </div>
    <%= submit_tag "Send Feedback" %>
    <% if local_assigns.has_key? :status_msg %>
        <p><%= status_msg %></p>
    <% end %>
 <% end %>

app/views/youtube/youtubeListProva.html.erb
<%=@response%>