config/routes.rb
Rails.application.routes.draw do   
  resources :affiliations
  resources :reviews
  resources :videos, only: [:index, :new, :create]
  resources :video_uploads, only: [:new, :create]
  root 'pages#home'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/profile' => 'profile#index'
  get '/profile/nameandrole' => 'profile#nameandrole'

  get '/cliente' => 'cliente#search'
  get '/cliente/function' => 'cliente#function'
  get '/cliente/managerprofile' => 'cliente#visualize'
  get '/cliente/events' => 'cliente#events' 

  # get '/cliente/createEvent' => 'cliente#createEvent'
  # get '/cliente/createEventConfirm' => 'cliente#createEventConfirm'

  # get "cliente/listEvent" , to: "cliente#listEvent"
  # get "cliente/deleteEvent" , to: "cliente#deleteEvent"

  # get "/cliente/event", to: "cliente#editEvent"
  # patch "/cliente/event", to: "cliente#reviewEvent"

  get '/manager' => 'manager#index'
  get '/manager/affiliazioni' => 'manager#affiliazioni'
  get '/manager/aziende' => 'manager#aziende'
  get '/manager/singleone' => 'manager#singleone'
  get '/manager/events' => 'manager#events' 

  get '/azienda' => 'azienda#index'
  get '/azienda/affiliazioni' => 'azienda#affiliazioni'
  
  get '/affiliations/accept' => 'affiliation#accept'

  get '/utility/annulla' => 'utility#annulla'
  
  get '/reviews' => 'review#index'
  # Defines the root path route ("/")
  # root "articles#index"
  get "calendar/createCalendar" , to: "calendar#create"
  get "calendar/updateCalendar" , to: "calendar#update"
  get "calendar/deleteCalendar" , to: "calendar#delete"

  get "calendar/createEvent" , to: "calendar#createEvent"
  post "calendar/createEventConfirm" , to: "calendar#createEventConfirm"
  get "calendar/createEventConfirm" , to: "calendar#createEventConfirm"
  get "calendar/listEvent" , to: "calendar#listEvent"
  get "calendar/deleteEvent" , to: "calendar#deleteEvent"

  get "/event", to: "calendar#editEvent"
  patch "/event", to: "calendar#reviewEvent"

  get "/YTProva", to: "youtube#youtubeListProva"

  get "/oauth2callback", to: "youtube#oauth2callback"

  #per yt
  get "/inizio", to: "yt_menu#index"
  get "/videos", to: "videos#index"
  get "/provayt1", to: "youtube#list"
  get "/provayt2", to: "youtube#youtubeListProva"
  get "/provayt3", to: "youtube#upload"
  post 'upload_video', to: 'youtube#upload', as: 'upload'

  get "/list_subs", to: "youtube#list_subs"
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  before_action :set_affiliation, only: %i[ show edit update destroy ]

  # GET /affiliations or /affiliations.json
  def index
    @affiliations = Affiliation.all
  end

  # GET /affiliations/1 or /affiliations/1.json
  def show
  end

  # GET /affiliations/new
  def new
    @affiliation = Affiliation.new

    @azienda=params[:azienda]
    
    if current_user.ruolo=="cliente"
      @cliente= current_user.id
      @manager= params[:manager]
    else 
      @cliente= params[:cliente]
      @manager= current_user.id
    end


  end

  # GET /affiliations/1/edit
  def edit
  end

 # GET /affiliations/accept?id=...

  def accept
    @affiliazione= Affiliation.find(params[:id])
    @affiliazione.update_attribute(:status, "accepted")
  end

  # POST /affiliations or /affiliations.json
  def create
    @affiliation = Affiliation.new(affiliation_params)
    @cliente= affiliation_params[:cliente]
    @manager= affiliation_params[:manager]
    @azienda= affiliation_params[:azienda]
    respond_to do |format|
      if @affiliation.save
        if current_user.ruolo=="cliente"
          format.html { redirect_to "/cliente/managerprofile?id="+@manager}
          format.json { render :show, status: :created, location: @affiliation }
        end
        if current_user.ruolo=="manager"
          format.html { redirect_to "/manager"}
          format.json { render :show, status: :created, location: @affiliation }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliations/1 or /affiliations/1.json
  def update
    respond_to do |format|
      if @affiliation.update(affiliation_params)
        format.html { redirect_to affiliation_url(@affiliation), notice: "Affiliation was successfully updated." }
        format.json { render :show, status: :ok, location: @affiliation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliations/1 or /affiliations/1.json
  def destroy
    @manager=@affiliation.manager
    @affiliation.destroy

    respond_to do |format|
      if current_user.ruolo=="cliente"
        format.html { redirect_to "/cliente/managerprofile?id="+@manager }
      else 
        format.html { redirect_to "/manager/affiliazioni"}
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
      @affiliation.update_attribute(:status, "accepted")
      respond_to do |format|
        if current_user.ruolo=="manager"
          format.html { redirect_to "/manager/affiliazioni"}
        end
        if current_user.ruolo=="azienda"
          format.html { redirect_to "/azienda/affiliazioni"}
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def affiliation_params
      params.require(:affiliation).permit(:cliente, :manager, :azienda, :status)
    end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/_affiliation.html.erb
<div id="<%= dom_id affiliation %>">
  <p>
    <strong>Cliente:</strong>
    <%= affiliation.cliente %>
  </p>

  <p>
    <strong>Manager:</strong>
    <%= affiliation.manager %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= affiliation.status %>
  </p>

</div>

app/views/affiliations/_form.html.erb
<%= form_with(model: affiliation) do |form| %>
  <% if affiliation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(affiliation.errors.count, "error") %> prohibited this affiliation from being saved:</h2>

      <ul>
        <% affiliation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div hidden>
    <%= form.text_field :cliente, value: @cliente%>
  </div>

  <div hidden>
    <%= form.text_field :manager, value: @manager %>
  </div>

  <div hidden>
    <%= form.text_field :azienda, value: @azienda %>
  </div>

  <div hidden>
    <%= form.text_field :status, value:"pending"%>
  </div>

  <div>
    <%= form.submit class:"btn btn-outline-danger ms-1", style:"width:200px"%>
    
  </div>
<% end %>

app/views/affiliations/edit.html.erb
<!DOCTYPE html>
<html amp >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  
  <title>ManageMyYoutube</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Heebo:100,300,400,500,700,800,900" rel="stylesheet">

    <script async  src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
    
</head>
<body>

  
<section class="cid-rslFJC9ynI" id="menu01-4n">
	
	<!-- mine-navbar -->
	<nav class="mine-navbar mine-navbar-dropdown mine-navbar-expand-lg mine-navbar-fixed-top">
		<div class="menu-mine-container mine-container-fluid">
			
			<div class="mine-navbar-brand">
				<div class="mine-navbar-logo">
					<img src="/assets/local/logomyytmanager.png" style="width:80px;padding-right:10px">
				</div>
				<span class="mine-navbar-caption-wrap"><a class="mine-navbar-caption mbr-semibold text-black text-decoration-none display-5" style="font-size: 2rem" href="/">ManageMyYoutube</a></span>
			</div>

            <div class="mine-btns">
                <% if current_user %>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7 text-decoration-none" href="/profile">Profile</a>
                    </div>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete, class:"mine-btnlogout" %>
                    </div>
                
                <% else%>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                
                    <a class="mine-btn mine-btn-md mine-btn-white mbr-semibold display-7" href="users/sign_in">Login</a>
                    <%= link_to "Login", new_user_session_path %>
                    
                </div>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                    <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7" href="users/sign_up">Sign Up</a>
                </div>
                <%end %>
            </div>

		</div>
	</nav>

	
	<!-- </div> -->
</section>

<div class="container pt-5 ">
  <div class="d-flex flex-column align-items-center justify-content-center">
    <div class="card mb-4 col-12">

    </div>
    <div>
      <%= render "form", affiliation: @affiliation %>
    </div>
  </div>
</div>
<br>

app/views/affiliations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Affiliations</h1>

<div id="affiliations">
  <% @affiliations.each do |affiliation| %>
    <%= render affiliation %>
    <p>
      <%= link_to "Show this affiliation", affiliation %>
    </p>
  <% end %>
</div>

<%= link_to "New affiliation", new_affiliation_path %>

app/views/affiliations/new.html.erb
<!DOCTYPE html>
<html amp >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  
  <title>ManageMyYoutube</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Heebo:100,300,400,500,700,800,900" rel="stylesheet">

    <script async  src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
    
</head>
<body>

  
<section class="cid-rslFJC9ynI" id="menu01-4n">
	
	<!-- mine-navbar -->
	<nav class="mine-navbar mine-navbar-dropdown mine-navbar-expand-lg mine-navbar-fixed-top">
		<div class="menu-mine-container mine-container-fluid">
			
			<div class="mine-navbar-brand">
				<div class="mine-navbar-logo">
					<img src="/assets/local/logomyytmanager.png" style="width:80px;padding-right:10px">
				</div>
				<span class="mine-navbar-caption-wrap"><a class="mine-navbar-caption mbr-semibold text-black text-decoration-none display-5" style="font-size: 2rem" href="/">ManageMyYoutube</a></span>
			</div>

            <div class="mine-btns">
                <% if current_user %>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7 text-decoration-none" href="/profile">Profile</a>
                    </div>
                    <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                        <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete, class:"mine-btnlogout" %>
                    </div>
                
                <% else%>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                
                    <a class="mine-btn mine-btn-md mine-btn-white mbr-semibold display-7" href="users/sign_in">Login</a>
                    <%= link_to "Login", new_user_session_path %>
                    
                </div>
                <div class="mine-navbar-buttons mbr-section-mine-btn d-flex">
                    <a class="mine-btn mine-btn-md mine-btn-black mbr-semibold display-7" href="users/sign_up">Sign Up</a>
                </div>
                <%end %>
            </div>

		</div>
	</nav>

	
	<!-- </div> -->
</section>

<%def withoutLast5(userAvatarUrl)
  if userAvatarUrl
    return userAvatarUrl[0..-6]+"s580-c"
  else 
    return "https://blogtimenow.com/wp-content/uploads/2014/06/hide-facebook-profile-picture-notification.jpg"
  end
end%>

<div class="container pt-5 " style="min-height:450px">
  <div class="d-flex flex-column align-items-center justify-content-center">
    <div class="card mb-4 col-12">

      <%if @azienda%>
        <div class="card-body text-center">
          <% if !User.find(@azienda.to_i).avatar.attached?%>
            <img src="<%=withoutLast5(User.find(@azienda.to_i).avatar_url)%>" alt="avatar"
            class="rounded-circle" style="width: 150px;">
          <% else %>
            <%= image_tag User.find(@azienda.to_i).avatar,class:"rounded-circle",height:150,width:150 %>
          <%end%>
          <h5 class="my-3 text-capitalize"><%= User.find(@azienda.to_i).full_name %></h5>
          <p class="text-muted text-capitalize"><%= User.find(@azienda.to_i).ruolo %></p>
        </div>

      <%else%>
      <div class="card-body text-center">

        <% if !User.find(@manager.to_i).avatar.attached?%>
          <img src="<%=withoutLast5(User.find(@manager.to_i).avatar_url)%>" alt="avatar"
          class="rounded-circle" style="width: 150px;">
        <% else %>
          <%= image_tag User.find(@manager.to_i).avatar,class:"rounded-circle",height:150,width:150 %>
        <%end%>
        
        <h5 class="my-3 text-capitalize"><%= User.find(@manager.to_i).full_name %></h5>
        <p class="text-muted text-capitalize"><%= User.find(@manager.to_i).ruolo %></p>
      </div>
      <%end%>

    </div>
    <div>
      <%= render "form", affiliation: @affiliation %>
    </div>
  </div>
</div>
<br>

app/views/affiliations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @affiliation %>

<div>
  <%= link_to "Edit this affiliation", edit_affiliation_path(@affiliation) %> |
  <%= link_to "Back to affiliations", affiliations_path %>

  <%= button_to "Destroy this affiliation", @affiliation, method: :delete %>
</div>